FROM golang:1.24.3 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -ldflags="-s -w" -o bootstrap ./cmd/prod/main.go

FROM public.ecr.aws/lambda/provided:al2

COPY --from=builder /app/bootstrap /var/task/
RUN chmod +x /var/task/bootstrap
