FROM golang:1.24.3 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -ldflags="-s -w" -o handler ./cmd/prod

FROM public.ecr.aws/lambda/go:1

COPY --from=builder /app/handler /var/task/

CMD ["handler"]
