package me

import "errors"

var (
	ErrExponentTooLarge          = errors.New("exponent too large to fit in int")
	ErrFailedToCreateJWKSRequest = errors.New("failed to create jwks request")
	ErrFailedToCreateRequest     = errors.New("failed to create request")
	ErrFailedToDecodeJWKS        = errors.New("failed to decode jwks JSON")
	ErrFailedToDecodeJWTHeader   = errors.New("failed to decode JWT header")
	ErrFailedToDecodeMetadata    = errors.New("failed to decode metadata")
	ErrFailedToFetchJWKS         = errors.New("failed to fetch jwks")
	ErrFailedToFetchMetadata     = errors.New("failed to fetch metadata")
	ErrFailedToParseJWTHeader    = errors.New("failed to parse JWT header")
	ErrFailedToParseLoginURL     = errors.New("failed to parse login endpoint URL")
	ErrInvalidAudience           = errors.New("invalid audience")
	ErrInvalidBase64URL          = errors.New("invalid base64url encoding")
	ErrInvalidE                  = errors.New("invalid e (exponent)")
	ErrInvalidExponent           = errors.New("invalid exponent value")
	ErrInvalidIssuer             = errors.New("unexpected issuer")
	ErrInvalidJWTFormat          = errors.New("invalid JWT format")
	ErrInvalidN                  = errors.New("invalid n (modulus)")
	ErrInvalidSigningAlg         = errors.New("unexpected signing method")
	ErrJWKNotFound               = errors.New("JWK not found")
	ErrJWKSetNil                 = errors.New("JWKSet is nil")
	ErrJWTParseFailed            = errors.New("failed to parse JWT")
	ErrMissingAudience           = errors.New("audience claim is missing")
	ErrMissingJWKSURI            = errors.New("missing jwks_uri in metadata response")
	ErrMissingKID                = errors.New("kid not found in JWT header")
	ErrMissingSubject            = errors.New("missing subject (sub)")
	ErrTokenExpired              = errors.New("token is expired")
	ErrUnexpectedStatusCode      = errors.New("unexpected status code from metadata endpoint")
)
