basePath: /
host: cognito-repeater-go.com
info:
  contact: {}
  description: |-
    A relay API for AWS Cognito login/logout/token verification
    Implemented in Go 1.24.3.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: Cognito Repeater API (Go)
  version: 1.0.0
paths: {}
schemes:
- https
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
