name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
          id-token: write
          contents: read

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::626635405187:role/cognito-repeater-go-cd-role
          aws-region: ap-northeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Docker image
        env:
          ACCOUNT_ID: ${{ steps.login-ecr.outputs.registry }}
          REGION: ap-northeast-1 
        run: |
          REGISTRY="${{ steps.login-ecr.outputs.registry }}"
          IMAGE_URI="$REGISTRY/cognito-repeater-go:main-${{ github.sha }}"
          
          docker build -t "$IMAGE_URI" -f Dockerfile.prod .
          docker push "$IMAGE_URI"

      - name: Update Lambda function code
        run: |
          REGISTRY="${{ steps.login-ecr.outputs.registry }}"
          aws lambda update-function-code \
            --function-name cognito-repeater-go \
            --image-uri "$REGISTRY/cognito-repeater-go:main-${{ github.sha }}" \
            | jq 'del(.Environment.Variables)'
